# Generated by Django 4.2.13 on 2024-07-27 14:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedi', '0003_rename_petimage_petpost_rename_is_active_pet_adopt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='dob',
        ),
        migrations.AddField(
            model_name='pet',
            name='age',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AddField(
            model_name='pet',
            name='petpfp',
            field=models.ImageField(null=True, upload_to='pet_pfp/'),
        ),
        migrations.AddField(
            model_name='pet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='matched_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='petpost',
            name='image',
            field=models.ImageField(null=True, upload_to='pet_images/'),
        ),
    ]
