# Generated by Django 4.2.13 on 2024-07-27 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedi', '0004_remove_pet_dob_pet_age_pet_petpfp_pet_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='created_at',
            new_name='message_created_at',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='petpost',
            old_name='pet',
            new_name='pet_details',
        ),
        migrations.RenameField(
            model_name='petpost',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='message',
            name='pet',
        ),
    ]
