# Generated by Django 4.2.13 on 2024-07-27 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedi', '0006_remove_like_like_like_like_count_alter_like_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='user1',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='matches_initiated', to=settings.AUTH_USER_MODEL),
        ),
    ]
